// Code generated by re2c 3.1, DO NOT EDIT.
package re2go

// PYTHON NAME: RE_FILTER
// Original pattern: (?i)\W*(Drucken|E-?Mail|Facebook|Flipboard|Google|Instagram|Linkedin|Mail|PDF|Pinterest|Pocket|Print|QQ|Reddit|Twitter|WeChat|WeiBo|Whatsapp|Xing|Mehr zum Thema:?|More on this.{,8})$
func IsTextFilter(input string) bool {
	var cursor, marker int
	input += string(rune(0)) // add terminating null
	limit := len(input) - 1  // limit points at the terminating null
	_ = marker

	// Variable for capturing parentheses (twice the number of groups).
	var YYMAXNMATCH int = 1

	yypmatch := make([]int, YYMAXNMATCH*2)
	var yynmatch int
	_ = yynmatch

	// Autogenerated tag variables used by the lexer to track tag values.
	var yyt1 int
	_ = yyt1

	var found bool
	for {
		{
			var yych byte
			yych = input[cursor]
			switch yych {
			case 0x00:
				fallthrough
			case 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, '\t', '\n', '\v', '\f', '\r', 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, ' ', '!', '"', '#', '$', '%', '&', '\'', '(', ')', '*', '+', ',', '-', '.', '/':
				fallthrough
			case ':', ';', '<', '=', '>', '?', '@':
				fallthrough
			case '[', '\\', ']', '^':
				fallthrough
			case '`':
				fallthrough
			case '{', '|', '}', '~', 0x7F:
				if limit <= cursor {
					goto yy145
				}
				yyt1 = cursor
				goto yy1
			case 'D':
				fallthrough
			case 'd':
				yyt1 = cursor
				goto yy4
			case 'E':
				fallthrough
			case 'e':
				yyt1 = cursor
				goto yy5
			case 'F':
				fallthrough
			case 'f':
				yyt1 = cursor
				goto yy6
			case 'G':
				fallthrough
			case 'g':
				yyt1 = cursor
				goto yy7
			case 'I':
				fallthrough
			case 'i':
				yyt1 = cursor
				goto yy8
			case 'L':
				fallthrough
			case 'l':
				yyt1 = cursor
				goto yy9
			case 'M':
				fallthrough
			case 'm':
				yyt1 = cursor
				goto yy10
			case 'P':
				fallthrough
			case 'p':
				yyt1 = cursor
				goto yy11
			case 'Q':
				fallthrough
			case 'q':
				yyt1 = cursor
				goto yy12
			case 'R':
				fallthrough
			case 'r':
				yyt1 = cursor
				goto yy13
			case 'T':
				fallthrough
			case 't':
				yyt1 = cursor
				goto yy14
			case 'W':
				fallthrough
			case 'w':
				yyt1 = cursor
				goto yy15
			case 'X':
				fallthrough
			case 'x':
				yyt1 = cursor
				goto yy16
			case 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xDB, 0xDC, 0xDD, 0xDE, 0xDF:
				yyt1 = cursor
				goto yy17
			case 0xE0:
				yyt1 = cursor
				goto yy18
			case 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xEB, 0xEC, 0xED, 0xEE, 0xEF:
				yyt1 = cursor
				goto yy19
			case 0xF0:
				yyt1 = cursor
				goto yy20
			case 0xF1, 0xF2, 0xF3:
				yyt1 = cursor
				goto yy21
			case 0xF4:
				yyt1 = cursor
				goto yy22
			default:
				goto yy3
			}
		yy1:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy23
			case 'E':
				fallthrough
			case 'e':
				goto yy25
			case 'F':
				fallthrough
			case 'f':
				goto yy26
			case 'G':
				fallthrough
			case 'g':
				goto yy27
			case 'I':
				fallthrough
			case 'i':
				goto yy28
			case 'L':
				fallthrough
			case 'l':
				goto yy29
			case 'M':
				fallthrough
			case 'm':
				goto yy30
			case 'P':
				fallthrough
			case 'p':
				goto yy31
			case 'Q':
				fallthrough
			case 'q':
				goto yy32
			case 'R':
				fallthrough
			case 'r':
				goto yy33
			case 'T':
				fallthrough
			case 't':
				goto yy34
			case 'W':
				fallthrough
			case 'w':
				goto yy35
			case 'X':
				fallthrough
			case 'x':
				goto yy36
			default:
				goto yy2
			}
		yy2:
			{
				found = false
				continue
			}
		yy3:
			cursor++
			goto yy2
		yy4:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy37
			default:
				goto yy2
			}
		yy5:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case '-':
				goto yy38
			case 'M':
				fallthrough
			case 'm':
				goto yy39
			default:
				goto yy2
			}
		yy6:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy40
			case 'L':
				fallthrough
			case 'l':
				goto yy41
			default:
				goto yy2
			}
		yy7:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy42
			default:
				goto yy2
			}
		yy8:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy43
			default:
				goto yy2
			}
		yy9:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy44
			default:
				goto yy2
			}
		yy10:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy45
			case 'E':
				fallthrough
			case 'e':
				goto yy46
			case 'O':
				fallthrough
			case 'o':
				goto yy47
			default:
				goto yy2
			}
		yy11:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy48
			case 'I':
				fallthrough
			case 'i':
				goto yy49
			case 'O':
				fallthrough
			case 'o':
				goto yy50
			case 'R':
				fallthrough
			case 'r':
				goto yy51
			default:
				goto yy2
			}
		yy12:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Q':
				fallthrough
			case 'q':
				goto yy52
			default:
				goto yy2
			}
		yy13:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy54
			default:
				goto yy2
			}
		yy14:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'W':
				fallthrough
			case 'w':
				goto yy55
			default:
				goto yy2
			}
		yy15:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy56
			case 'H':
				fallthrough
			case 'h':
				goto yy57
			default:
				goto yy2
			}
		yy16:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy58
			default:
				goto yy2
			}
		yy17:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy59
			default:
				goto yy2
			}
		yy18:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy60
			default:
				goto yy2
			}
		yy19:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy60
			default:
				goto yy2
			}
		yy20:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy61
			default:
				goto yy2
			}
		yy21:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy61
			default:
				goto yy2
			}
		yy22:
			cursor++
			marker = cursor
			yych = input[cursor]
			switch yych {
			case 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F:
				goto yy61
			default:
				goto yy2
			}
		yy23:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy37
			default:
				goto yy24
			}
		yy24:
			cursor = marker
			goto yy2
		yy25:
			cursor++
			yych = input[cursor]
			switch yych {
			case '-':
				goto yy38
			case 'M':
				fallthrough
			case 'm':
				goto yy39
			default:
				goto yy24
			}
		yy26:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy40
			case 'L':
				fallthrough
			case 'l':
				goto yy41
			default:
				goto yy24
			}
		yy27:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy42
			default:
				goto yy24
			}
		yy28:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy43
			default:
				goto yy24
			}
		yy29:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy44
			default:
				goto yy24
			}
		yy30:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy45
			case 'E':
				fallthrough
			case 'e':
				goto yy46
			case 'O':
				fallthrough
			case 'o':
				goto yy47
			default:
				goto yy24
			}
		yy31:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy48
			case 'I':
				fallthrough
			case 'i':
				goto yy49
			case 'O':
				fallthrough
			case 'o':
				goto yy50
			case 'R':
				fallthrough
			case 'r':
				goto yy51
			default:
				goto yy24
			}
		yy32:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Q':
				fallthrough
			case 'q':
				goto yy52
			default:
				goto yy24
			}
		yy33:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy54
			default:
				goto yy24
			}
		yy34:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'W':
				fallthrough
			case 'w':
				goto yy55
			default:
				goto yy24
			}
		yy35:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy56
			case 'H':
				fallthrough
			case 'h':
				goto yy57
			default:
				goto yy24
			}
		yy36:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy58
			default:
				goto yy24
			}
		yy37:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy62
			default:
				goto yy24
			}
		yy38:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy39
			default:
				goto yy24
			}
		yy39:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy45
			default:
				goto yy24
			}
		yy40:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy63
			default:
				goto yy24
			}
		yy41:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy64
			default:
				goto yy24
			}
		yy42:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy65
			default:
				goto yy24
			}
		yy43:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy66
			default:
				goto yy24
			}
		yy44:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy67
			default:
				goto yy24
			}
		yy45:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy68
			default:
				goto yy24
			}
		yy46:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy69
			default:
				goto yy24
			}
		yy47:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy70
			default:
				goto yy24
			}
		yy48:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'F':
				fallthrough
			case 'f':
				goto yy52
			default:
				goto yy24
			}
		yy49:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy71
			default:
				goto yy24
			}
		yy50:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy72
			default:
				goto yy24
			}
		yy51:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy73
			default:
				goto yy24
			}
		yy52:
			cursor++
		yy53:
			yynmatch = 1
			yypmatch[0] = yyt1
			yypmatch[1] = cursor
			{
				found = true
				continue
			}
		yy54:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy74
			default:
				goto yy24
			}
		yy55:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy75
			default:
				goto yy24
			}
		yy56:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy76
			case 'I':
				fallthrough
			case 'i':
				goto yy77
			default:
				goto yy24
			}
		yy57:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy78
			default:
				goto yy24
			}
		yy58:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy79
			default:
				goto yy24
			}
		yy59:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy23
			case 'E':
				fallthrough
			case 'e':
				goto yy25
			case 'F':
				fallthrough
			case 'f':
				goto yy26
			case 'G':
				fallthrough
			case 'g':
				goto yy27
			case 'I':
				fallthrough
			case 'i':
				goto yy28
			case 'L':
				fallthrough
			case 'l':
				goto yy29
			case 'M':
				fallthrough
			case 'm':
				goto yy30
			case 'P':
				fallthrough
			case 'p':
				goto yy31
			case 'Q':
				fallthrough
			case 'q':
				goto yy32
			case 'R':
				fallthrough
			case 'r':
				goto yy33
			case 'T':
				fallthrough
			case 't':
				goto yy34
			case 'W':
				fallthrough
			case 'w':
				goto yy35
			case 'X':
				fallthrough
			case 'x':
				goto yy36
			default:
				goto yy24
			}
		yy60:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy59
			default:
				goto yy24
			}
		yy61:
			cursor++
			yych = input[cursor]
			switch yych {
			case 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0x9B, 0x9C, 0x9D, 0x9E, 0x9F, 0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xBB, 0xBC, 0xBD, 0xBE, 0xBF:
				goto yy60
			default:
				goto yy24
			}
		yy62:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'C':
				fallthrough
			case 'c':
				goto yy80
			default:
				goto yy24
			}
		yy63:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy81
			default:
				goto yy24
			}
		yy64:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy82
			default:
				goto yy24
			}
		yy65:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy83
			default:
				goto yy24
			}
		yy66:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy84
			default:
				goto yy24
			}
		yy67:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'K':
				fallthrough
			case 'k':
				goto yy85
			default:
				goto yy24
			}
		yy68:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy52
			default:
				goto yy24
			}
		yy69:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy86
			default:
				goto yy24
			}
		yy70:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy87
			default:
				goto yy24
			}
		yy71:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy88
			default:
				goto yy24
			}
		yy72:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'K':
				fallthrough
			case 'k':
				goto yy89
			default:
				goto yy24
			}
		yy73:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy90
			default:
				goto yy24
			}
		yy74:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy91
			default:
				goto yy24
			}
		yy75:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy92
			default:
				goto yy24
			}
		yy76:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy93
			default:
				goto yy24
			}
		yy77:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy94
			default:
				goto yy24
			}
		yy78:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy95
			default:
				goto yy24
			}
		yy79:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy52
			default:
				goto yy24
			}
		yy80:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'K':
				fallthrough
			case 'k':
				goto yy96
			default:
				goto yy24
			}
		yy81:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy97
			default:
				goto yy24
			}
		yy82:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'B':
				fallthrough
			case 'b':
				goto yy98
			default:
				goto yy24
			}
		yy83:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'L':
				fallthrough
			case 'l':
				goto yy99
			default:
				goto yy24
			}
		yy84:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy100
			default:
				goto yy24
			}
		yy85:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy101
			default:
				goto yy24
			}
		yy86:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy102
			default:
				goto yy24
			}
		yy87:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy103
			default:
				goto yy24
			}
		yy88:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy104
			default:
				goto yy24
			}
		yy89:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy90
			default:
				goto yy24
			}
		yy90:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy52
			default:
				goto yy24
			}
		yy91:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy90
			default:
				goto yy24
			}
		yy92:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy105
			default:
				goto yy24
			}
		yy93:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy90
			default:
				goto yy24
			}
		yy94:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy52
			default:
				goto yy24
			}
		yy95:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy106
			default:
				goto yy24
			}
		yy96:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy107
			default:
				goto yy24
			}
		yy97:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy108
			default:
				goto yy24
			}
		yy98:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy109
			default:
				goto yy24
			}
		yy99:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy52
			default:
				goto yy24
			}
		yy100:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'G':
				fallthrough
			case 'g':
				goto yy110
			default:
				goto yy24
			}
		yy101:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy111
			default:
				goto yy24
			}
		yy102:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'Z':
				fallthrough
			case 'z':
				goto yy112
			default:
				goto yy24
			}
		yy103:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy113
			default:
				goto yy24
			}
		yy104:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy114
			default:
				goto yy24
			}
		yy105:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy115
			default:
				goto yy24
			}
		yy106:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy116
			default:
				goto yy24
			}
		yy107:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy52
			default:
				goto yy24
			}
		yy108:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'O':
				fallthrough
			case 'o':
				goto yy117
			default:
				goto yy24
			}
		yy109:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy118
			default:
				goto yy24
			}
		yy110:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy119
			default:
				goto yy24
			}
		yy111:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy107
			default:
				goto yy24
			}
		yy112:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'U':
				fallthrough
			case 'u':
				goto yy120
			default:
				goto yy24
			}
		yy113:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'N':
				fallthrough
			case 'n':
				goto yy121
			default:
				goto yy24
			}
		yy114:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy122
			default:
				goto yy24
			}
		yy115:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy52
			default:
				goto yy24
			}
		yy116:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy123
			default:
				goto yy24
			}
		yy117:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'K':
				fallthrough
			case 'k':
				goto yy52
			default:
				goto yy24
			}
		yy118:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'R':
				fallthrough
			case 'r':
				goto yy124
			default:
				goto yy24
			}
		yy119:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy125
			default:
				goto yy24
			}
		yy120:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy126
			default:
				goto yy24
			}
		yy121:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy127
			default:
				goto yy24
			}
		yy122:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy90
			default:
				goto yy24
			}
		yy123:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'P':
				fallthrough
			case 'p':
				goto yy52
			default:
				goto yy24
			}
		yy124:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'D':
				fallthrough
			case 'd':
				goto yy52
			default:
				goto yy24
			}
		yy125:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy52
			default:
				goto yy24
			}
		yy126:
			cursor++
			yych = input[cursor]
			switch yych {
			case ' ':
				goto yy128
			default:
				goto yy24
			}
		yy127:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy129
			default:
				goto yy24
			}
		yy128:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'T':
				fallthrough
			case 't':
				goto yy130
			default:
				goto yy24
			}
		yy129:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy131
			default:
				goto yy24
			}
		yy130:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'H':
				fallthrough
			case 'h':
				goto yy132
			default:
				goto yy24
			}
		yy131:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'I':
				fallthrough
			case 'i':
				goto yy133
			default:
				goto yy24
			}
		yy132:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'E':
				fallthrough
			case 'e':
				goto yy134
			default:
				goto yy24
			}
		yy133:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'S':
				fallthrough
			case 's':
				goto yy135
			default:
				goto yy24
			}
		yy134:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'M':
				fallthrough
			case 'm':
				goto yy136
			default:
				goto yy24
			}
		yy135:
			cursor++
			yych = input[cursor]
			switch yych {
			case '.':
				goto yy137
			default:
				goto yy53
			}
		yy136:
			cursor++
			yych = input[cursor]
			switch yych {
			case 'A':
				fallthrough
			case 'a':
				goto yy138
			default:
				goto yy24
			}
		yy137:
			cursor++
			yych = input[cursor]
			switch yych {
			case '.':
				goto yy139
			default:
				goto yy53
			}
		yy138:
			cursor++
			yych = input[cursor]
			switch yych {
			case ':':
				goto yy52
			default:
				goto yy53
			}
		yy139:
			cursor++
			yych = input[cursor]
			switch yych {
			case '.':
				goto yy140
			default:
				goto yy53
			}
		yy140:
			cursor++
			yych = input[cursor]
			switch yych {
			case '.':
				goto yy141
			default:
				goto yy53
			}
		yy141:
			cursor++
			yych = input[cursor]
			switch yych {
			case '.':
				goto yy142
			default:
				goto yy53
			}
		yy142:
			cursor++
			yych = input[cursor]
			switch yych {
			case '.':
				goto yy143
			default:
				goto yy53
			}
		yy143:
			cursor++
			yych = input[cursor]
			switch yych {
			case '.':
				goto yy144
			default:
				goto yy53
			}
		yy144:
			cursor++
			yych = input[cursor]
			switch yych {
			case '.':
				goto yy52
			default:
				goto yy53
			}
		yy145:
			{
				return found
			}
		}

	}
}
